auth_key : '4049494949409404040404040'

language_code : "FR"

path : '/Users/javier/IdeaProjects/vonfreiren.github.io/_posts/'
file : '2021-12-26-achieve-economic-independence.html'

languages : ['DE', 'ES', 'FR']

destination_path: '/Users/javier/IdeaProjects/vonfreiren.github.io/_posts/'
destination_path_de: '/Users/javier/IdeaProjects/vonfreiren.github.io/_german/'
destination_path_es: '/Users/javier/IdeaProjects/vonfreiren.github.io/_spanish/'
destination_path_fr: '/Users/javier/IdeaProjects/vonfreiren.github.io/_french/'