auth_key : 'XDRIRIRIRIRIRIR:fx'

language_code : "ES"

path : '/Users/javier/IdeaProjects/vonfreiren.github.io/_posts/'
file : '2023-02-22-ethereum-shanghai.md'

destination_path: '/Users/javier/IdeaProjects/vonfreiren.github.io/_spanish/'